/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitCaseRouteImport } from './routes/submit-case'
import { Route as LawyersRouteImport } from './routes/lawyers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSqlRouteImport } from './routes/admin.sql'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLawyersRouteImport } from './routes/admin.lawyers'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'

const SubmitCaseRoute = SubmitCaseRouteImport.update({
  id: '/submit-case',
  path: '/submit-case',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyersRoute = LawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSqlRoute = AdminSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyersRoute = AdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/submit-case': typeof SubmitCaseRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/sql': typeof AdminSqlRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/submit-case': typeof SubmitCaseRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/sql': typeof AdminSqlRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/admin': typeof AdminIndexRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lawyers': typeof LawyersRoute
  '/submit-case': typeof SubmitCaseRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/sql': typeof AdminSqlRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/submit-case'
    | '/admin/cases'
    | '/admin/flags'
    | '/admin/lawyers'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/permissions'
    | '/admin/sql'
    | '/admin/users'
    | '/cases/$caseId'
    | '/admin/'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/submit-case'
    | '/admin/cases'
    | '/admin/flags'
    | '/admin/lawyers'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/permissions'
    | '/admin/sql'
    | '/admin/users'
    | '/cases/$caseId'
    | '/admin'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/lawyers'
    | '/submit-case'
    | '/admin/cases'
    | '/admin/flags'
    | '/admin/lawyers'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/permissions'
    | '/admin/sql'
    | '/admin/users'
    | '/cases/$caseId'
    | '/admin/'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LawyersRoute: typeof LawyersRoute
  SubmitCaseRoute: typeof SubmitCaseRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-case': {
      id: '/submit-case'
      path: '/submit-case'
      fullPath: '/submit-case'
      preLoaderRoute: typeof SubmitCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyers': {
      id: '/lawyers'
      path: '/lawyers'
      fullPath: '/lawyers'
      preLoaderRoute: typeof LawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sql': {
      id: '/admin/sql'
      path: '/sql'
      fullPath: '/admin/sql'
      preLoaderRoute: typeof AdminSqlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyers': {
      id: '/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AdminLawyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminLawyersRoute: typeof AdminLawyersRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSqlRoute: typeof AdminSqlRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminLawyersRoute: AdminLawyersRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSqlRoute: AdminSqlRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LawyersRoute: LawyersRoute,
  SubmitCaseRoute: SubmitCaseRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
